// Generated by gencpp from file camera_srv_definitions/cleanup.msg
// DO NOT EDIT!


#ifndef CAMERA_SRV_DEFINITIONS_MESSAGE_CLEANUP_H
#define CAMERA_SRV_DEFINITIONS_MESSAGE_CLEANUP_H

#include <ros/service_traits.h>


#include <camera_srv_definitions/cleanupRequest.h>
#include <camera_srv_definitions/cleanupResponse.h>


namespace camera_srv_definitions
{

struct cleanup
{

typedef cleanupRequest Request;
typedef cleanupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cleanup
} // namespace camera_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_srv_definitions::cleanup > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::camera_srv_definitions::cleanup&) { return value(); }
};

template<>
struct DataType< ::camera_srv_definitions::cleanup > {
  static const char* value()
  {
    return "camera_srv_definitions/cleanup";
  }

  static const char* value(const ::camera_srv_definitions::cleanup&) { return value(); }
};


// service_traits::MD5Sum< ::camera_srv_definitions::cleanupRequest> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::cleanup > 
template<>
struct MD5Sum< ::camera_srv_definitions::cleanupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::cleanup >::value();
  }
  static const char* value(const ::camera_srv_definitions::cleanupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::cleanupRequest> should match 
// service_traits::DataType< ::camera_srv_definitions::cleanup > 
template<>
struct DataType< ::camera_srv_definitions::cleanupRequest>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::cleanup >::value();
  }
  static const char* value(const ::camera_srv_definitions::cleanupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_srv_definitions::cleanupResponse> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::cleanup > 
template<>
struct MD5Sum< ::camera_srv_definitions::cleanupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::cleanup >::value();
  }
  static const char* value(const ::camera_srv_definitions::cleanupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::cleanupResponse> should match 
// service_traits::DataType< ::camera_srv_definitions::cleanup > 
template<>
struct DataType< ::camera_srv_definitions::cleanupResponse>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::cleanup >::value();
  }
  static const char* value(const ::camera_srv_definitions::cleanupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_SRV_DEFINITIONS_MESSAGE_CLEANUP_H
