// Generated by gencpp from file camera_srv_definitions/do_ba.msg
// DO NOT EDIT!


#ifndef CAMERA_SRV_DEFINITIONS_MESSAGE_DO_BA_H
#define CAMERA_SRV_DEFINITIONS_MESSAGE_DO_BA_H

#include <ros/service_traits.h>


#include <camera_srv_definitions/do_baRequest.h>
#include <camera_srv_definitions/do_baResponse.h>


namespace camera_srv_definitions
{

struct do_ba
{

typedef do_baRequest Request;
typedef do_baResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct do_ba
} // namespace camera_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_srv_definitions::do_ba > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::camera_srv_definitions::do_ba&) { return value(); }
};

template<>
struct DataType< ::camera_srv_definitions::do_ba > {
  static const char* value()
  {
    return "camera_srv_definitions/do_ba";
  }

  static const char* value(const ::camera_srv_definitions::do_ba&) { return value(); }
};


// service_traits::MD5Sum< ::camera_srv_definitions::do_baRequest> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::do_ba > 
template<>
struct MD5Sum< ::camera_srv_definitions::do_baRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::do_ba >::value();
  }
  static const char* value(const ::camera_srv_definitions::do_baRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::do_baRequest> should match 
// service_traits::DataType< ::camera_srv_definitions::do_ba > 
template<>
struct DataType< ::camera_srv_definitions::do_baRequest>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::do_ba >::value();
  }
  static const char* value(const ::camera_srv_definitions::do_baRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_srv_definitions::do_baResponse> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::do_ba > 
template<>
struct MD5Sum< ::camera_srv_definitions::do_baResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::do_ba >::value();
  }
  static const char* value(const ::camera_srv_definitions::do_baResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::do_baResponse> should match 
// service_traits::DataType< ::camera_srv_definitions::do_ba > 
template<>
struct DataType< ::camera_srv_definitions::do_baResponse>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::do_ba >::value();
  }
  static const char* value(const ::camera_srv_definitions::do_baResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_SRV_DEFINITIONS_MESSAGE_DO_BA_H
