// Generated by gencpp from file camera_srv_definitions/stop_tracker.msg
// DO NOT EDIT!


#ifndef CAMERA_SRV_DEFINITIONS_MESSAGE_STOP_TRACKER_H
#define CAMERA_SRV_DEFINITIONS_MESSAGE_STOP_TRACKER_H

#include <ros/service_traits.h>


#include <camera_srv_definitions/stop_trackerRequest.h>
#include <camera_srv_definitions/stop_trackerResponse.h>


namespace camera_srv_definitions
{

struct stop_tracker
{

typedef stop_trackerRequest Request;
typedef stop_trackerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct stop_tracker
} // namespace camera_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_srv_definitions::stop_tracker > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::camera_srv_definitions::stop_tracker&) { return value(); }
};

template<>
struct DataType< ::camera_srv_definitions::stop_tracker > {
  static const char* value()
  {
    return "camera_srv_definitions/stop_tracker";
  }

  static const char* value(const ::camera_srv_definitions::stop_tracker&) { return value(); }
};


// service_traits::MD5Sum< ::camera_srv_definitions::stop_trackerRequest> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::stop_tracker > 
template<>
struct MD5Sum< ::camera_srv_definitions::stop_trackerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::stop_tracker >::value();
  }
  static const char* value(const ::camera_srv_definitions::stop_trackerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::stop_trackerRequest> should match 
// service_traits::DataType< ::camera_srv_definitions::stop_tracker > 
template<>
struct DataType< ::camera_srv_definitions::stop_trackerRequest>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::stop_tracker >::value();
  }
  static const char* value(const ::camera_srv_definitions::stop_trackerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_srv_definitions::stop_trackerResponse> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::stop_tracker > 
template<>
struct MD5Sum< ::camera_srv_definitions::stop_trackerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::stop_tracker >::value();
  }
  static const char* value(const ::camera_srv_definitions::stop_trackerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::stop_trackerResponse> should match 
// service_traits::DataType< ::camera_srv_definitions::stop_tracker > 
template<>
struct DataType< ::camera_srv_definitions::stop_trackerResponse>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::stop_tracker >::value();
  }
  static const char* value(const ::camera_srv_definitions::stop_trackerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_SRV_DEFINITIONS_MESSAGE_STOP_TRACKER_H
