// Generated by gencpp from file camera_srv_definitions/visualize_compound.msg
// DO NOT EDIT!


#ifndef CAMERA_SRV_DEFINITIONS_MESSAGE_VISUALIZE_COMPOUND_H
#define CAMERA_SRV_DEFINITIONS_MESSAGE_VISUALIZE_COMPOUND_H

#include <ros/service_traits.h>


#include <camera_srv_definitions/visualize_compoundRequest.h>
#include <camera_srv_definitions/visualize_compoundResponse.h>


namespace camera_srv_definitions
{

struct visualize_compound
{

typedef visualize_compoundRequest Request;
typedef visualize_compoundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visualize_compound
} // namespace camera_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_srv_definitions::visualize_compound > {
  static const char* value()
  {
    return "3e4836b712c6ddd8441b7c4e40288ca4";
  }

  static const char* value(const ::camera_srv_definitions::visualize_compound&) { return value(); }
};

template<>
struct DataType< ::camera_srv_definitions::visualize_compound > {
  static const char* value()
  {
    return "camera_srv_definitions/visualize_compound";
  }

  static const char* value(const ::camera_srv_definitions::visualize_compound&) { return value(); }
};


// service_traits::MD5Sum< ::camera_srv_definitions::visualize_compoundRequest> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::visualize_compound > 
template<>
struct MD5Sum< ::camera_srv_definitions::visualize_compoundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::visualize_compound >::value();
  }
  static const char* value(const ::camera_srv_definitions::visualize_compoundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::visualize_compoundRequest> should match 
// service_traits::DataType< ::camera_srv_definitions::visualize_compound > 
template<>
struct DataType< ::camera_srv_definitions::visualize_compoundRequest>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::visualize_compound >::value();
  }
  static const char* value(const ::camera_srv_definitions::visualize_compoundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_srv_definitions::visualize_compoundResponse> should match 
// service_traits::MD5Sum< ::camera_srv_definitions::visualize_compound > 
template<>
struct MD5Sum< ::camera_srv_definitions::visualize_compoundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_srv_definitions::visualize_compound >::value();
  }
  static const char* value(const ::camera_srv_definitions::visualize_compoundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_srv_definitions::visualize_compoundResponse> should match 
// service_traits::DataType< ::camera_srv_definitions::visualize_compound > 
template<>
struct DataType< ::camera_srv_definitions::visualize_compoundResponse>
{
  static const char* value()
  {
    return DataType< ::camera_srv_definitions::visualize_compound >::value();
  }
  static const char* value(const ::camera_srv_definitions::visualize_compoundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_SRV_DEFINITIONS_MESSAGE_VISUALIZE_COMPOUND_H
