// Generated by gencpp from file classifier_srv_definitions/classify.msg
// DO NOT EDIT!


#ifndef CLASSIFIER_SRV_DEFINITIONS_MESSAGE_CLASSIFY_H
#define CLASSIFIER_SRV_DEFINITIONS_MESSAGE_CLASSIFY_H

#include <ros/service_traits.h>


#include <classifier_srv_definitions/classifyRequest.h>
#include <classifier_srv_definitions/classifyResponse.h>


namespace classifier_srv_definitions
{

struct classify
{

typedef classifyRequest Request;
typedef classifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct classify
} // namespace classifier_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::classifier_srv_definitions::classify > {
  static const char* value()
  {
    return "6da3c30c72cafedd00b3379838f889d2";
  }

  static const char* value(const ::classifier_srv_definitions::classify&) { return value(); }
};

template<>
struct DataType< ::classifier_srv_definitions::classify > {
  static const char* value()
  {
    return "classifier_srv_definitions/classify";
  }

  static const char* value(const ::classifier_srv_definitions::classify&) { return value(); }
};


// service_traits::MD5Sum< ::classifier_srv_definitions::classifyRequest> should match 
// service_traits::MD5Sum< ::classifier_srv_definitions::classify > 
template<>
struct MD5Sum< ::classifier_srv_definitions::classifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::classifier_srv_definitions::classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::classifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::classifier_srv_definitions::classifyRequest> should match 
// service_traits::DataType< ::classifier_srv_definitions::classify > 
template<>
struct DataType< ::classifier_srv_definitions::classifyRequest>
{
  static const char* value()
  {
    return DataType< ::classifier_srv_definitions::classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::classifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::classifier_srv_definitions::classifyResponse> should match 
// service_traits::MD5Sum< ::classifier_srv_definitions::classify > 
template<>
struct MD5Sum< ::classifier_srv_definitions::classifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::classifier_srv_definitions::classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::classifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::classifier_srv_definitions::classifyResponse> should match 
// service_traits::DataType< ::classifier_srv_definitions::classify > 
template<>
struct DataType< ::classifier_srv_definitions::classifyResponse>
{
  static const char* value()
  {
    return DataType< ::classifier_srv_definitions::classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::classifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLASSIFIER_SRV_DEFINITIONS_MESSAGE_CLASSIFY_H
