// Generated by gencpp from file classifier_srv_definitions/mv_classify.msg
// DO NOT EDIT!


#ifndef CLASSIFIER_SRV_DEFINITIONS_MESSAGE_MV_CLASSIFY_H
#define CLASSIFIER_SRV_DEFINITIONS_MESSAGE_MV_CLASSIFY_H

#include <ros/service_traits.h>


#include <classifier_srv_definitions/mv_classifyRequest.h>
#include <classifier_srv_definitions/mv_classifyResponse.h>


namespace classifier_srv_definitions
{

struct mv_classify
{

typedef mv_classifyRequest Request;
typedef mv_classifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mv_classify
} // namespace classifier_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::classifier_srv_definitions::mv_classify > {
  static const char* value()
  {
    return "67bbe4821b0ec370f484928297d55f41";
  }

  static const char* value(const ::classifier_srv_definitions::mv_classify&) { return value(); }
};

template<>
struct DataType< ::classifier_srv_definitions::mv_classify > {
  static const char* value()
  {
    return "classifier_srv_definitions/mv_classify";
  }

  static const char* value(const ::classifier_srv_definitions::mv_classify&) { return value(); }
};


// service_traits::MD5Sum< ::classifier_srv_definitions::mv_classifyRequest> should match 
// service_traits::MD5Sum< ::classifier_srv_definitions::mv_classify > 
template<>
struct MD5Sum< ::classifier_srv_definitions::mv_classifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::classifier_srv_definitions::mv_classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::mv_classifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::classifier_srv_definitions::mv_classifyRequest> should match 
// service_traits::DataType< ::classifier_srv_definitions::mv_classify > 
template<>
struct DataType< ::classifier_srv_definitions::mv_classifyRequest>
{
  static const char* value()
  {
    return DataType< ::classifier_srv_definitions::mv_classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::mv_classifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::classifier_srv_definitions::mv_classifyResponse> should match 
// service_traits::MD5Sum< ::classifier_srv_definitions::mv_classify > 
template<>
struct MD5Sum< ::classifier_srv_definitions::mv_classifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::classifier_srv_definitions::mv_classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::mv_classifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::classifier_srv_definitions::mv_classifyResponse> should match 
// service_traits::DataType< ::classifier_srv_definitions::mv_classify > 
template<>
struct DataType< ::classifier_srv_definitions::mv_classifyResponse>
{
  static const char* value()
  {
    return DataType< ::classifier_srv_definitions::mv_classify >::value();
  }
  static const char* value(const ::classifier_srv_definitions::mv_classifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLASSIFIER_SRV_DEFINITIONS_MESSAGE_MV_CLASSIFY_H
