(cl:defpackage classifier_srv_definitions-srv
  (:use )
  (:export
   "SEGMENT_AND_CLASSIFY"
   "<SEGMENT_AND_CLASSIFY-REQUEST>"
   "SEGMENT_AND_CLASSIFY-REQUEST"
   "<SEGMENT_AND_CLASSIFY-RESPONSE>"
   "SEGMENT_AND_CLASSIFY-RESPONSE"
   "MV_CLASSIFY"
   "<MV_CLASSIFY-REQUEST>"
   "MV_CLASSIFY-REQUEST"
   "<MV_CLASSIFY-RESPONSE>"
   "MV_CLASSIFY-RESPONSE"
   "CLASSIFY"
   "<CLASSIFY-REQUEST>"
   "CLASSIFY-REQUEST"
   "<CLASSIFY-RESPONSE>"
   "CLASSIFY-RESPONSE"
  ))

