// Generated by gencpp from file object_tracker_msg_definitions/ObjectInfo.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKER_MSG_DEFINITIONS_MESSAGE_OBJECTINFO_H
#define OBJECT_TRACKER_MSG_DEFINITIONS_MESSAGE_OBJECTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Quaternion.h>

namespace object_tracker_msg_definitions
{
template <class ContainerAllocator>
struct ObjectInfo_
{
  typedef ObjectInfo_<ContainerAllocator> Type;

  ObjectInfo_()
    : translation()
    , rotation()
    , confidence(0.0)  {
    }
  ObjectInfo_(const ContainerAllocator& _alloc)
    : translation(_alloc)
    , rotation(_alloc)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _translation_type;
  _translation_type translation;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _rotation_type;
  _rotation_type rotation;

   typedef double _confidence_type;
  _confidence_type confidence;




  typedef boost::shared_ptr< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInfo_

typedef ::object_tracker_msg_definitions::ObjectInfo_<std::allocator<void> > ObjectInfo;

typedef boost::shared_ptr< ::object_tracker_msg_definitions::ObjectInfo > ObjectInfoPtr;
typedef boost::shared_ptr< ::object_tracker_msg_definitions::ObjectInfo const> ObjectInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_tracker_msg_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'object_tracker_msg_definitions': ['/home/ros/catkin_ws/src/v4r_ros_wrappers/object_tracker_msg_definitions/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fdf9fc2b5a15076288ba7c1a2a70536d";
  }

  static const char* value(const ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfdf9fc2b5a150762ULL;
  static const uint64_t static_value2 = 0x88ba7c1a2a70536dULL;
};

template<class ContainerAllocator>
struct DataType< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_tracker_msg_definitions/ObjectInfo";
  }

  static const char* value(const ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This represents the transform between camera and object frame in free space.\n\
# With the confidence of the tracking\n\
\n\
geometry_msgs/Vector3 translation\n\
geometry_msgs/Quaternion rotation\n\
\n\
float64 confidence\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.translation);
      stream.next(m.rotation);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_tracker_msg_definitions::ObjectInfo_<ContainerAllocator>& v)
  {
    s << indent << "translation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.translation);
    s << indent << "rotation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.rotation);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_TRACKER_MSG_DEFINITIONS_MESSAGE_OBJECTINFO_H
