// Generated by gencpp from file object_tracker_srv_definitions/change_tracking_model.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_CHANGE_TRACKING_MODEL_H
#define OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_CHANGE_TRACKING_MODEL_H

#include <ros/service_traits.h>


#include <object_tracker_srv_definitions/change_tracking_modelRequest.h>
#include <object_tracker_srv_definitions/change_tracking_modelResponse.h>


namespace object_tracker_srv_definitions
{

struct change_tracking_model
{

typedef change_tracking_modelRequest Request;
typedef change_tracking_modelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct change_tracking_model
} // namespace object_tracker_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_tracker_srv_definitions::change_tracking_model > {
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::object_tracker_srv_definitions::change_tracking_model&) { return value(); }
};

template<>
struct DataType< ::object_tracker_srv_definitions::change_tracking_model > {
  static const char* value()
  {
    return "object_tracker_srv_definitions/change_tracking_model";
  }

  static const char* value(const ::object_tracker_srv_definitions::change_tracking_model&) { return value(); }
};


// service_traits::MD5Sum< ::object_tracker_srv_definitions::change_tracking_modelRequest> should match 
// service_traits::MD5Sum< ::object_tracker_srv_definitions::change_tracking_model > 
template<>
struct MD5Sum< ::object_tracker_srv_definitions::change_tracking_modelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_tracker_srv_definitions::change_tracking_model >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_tracker_srv_definitions::change_tracking_modelRequest> should match 
// service_traits::DataType< ::object_tracker_srv_definitions::change_tracking_model > 
template<>
struct DataType< ::object_tracker_srv_definitions::change_tracking_modelRequest>
{
  static const char* value()
  {
    return DataType< ::object_tracker_srv_definitions::change_tracking_model >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_tracker_srv_definitions::change_tracking_modelResponse> should match 
// service_traits::MD5Sum< ::object_tracker_srv_definitions::change_tracking_model > 
template<>
struct MD5Sum< ::object_tracker_srv_definitions::change_tracking_modelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_tracker_srv_definitions::change_tracking_model >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_tracker_srv_definitions::change_tracking_modelResponse> should match 
// service_traits::DataType< ::object_tracker_srv_definitions::change_tracking_model > 
template<>
struct DataType< ::object_tracker_srv_definitions::change_tracking_modelResponse>
{
  static const char* value()
  {
    return DataType< ::object_tracker_srv_definitions::change_tracking_model >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_CHANGE_TRACKING_MODEL_H
