// Generated by gencpp from file object_tracker_srv_definitions/change_tracking_modelRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_CHANGE_TRACKING_MODELREQUEST_H
#define OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_CHANGE_TRACKING_MODELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_tracker_srv_definitions
{
template <class ContainerAllocator>
struct change_tracking_modelRequest_
{
  typedef change_tracking_modelRequest_<ContainerAllocator> Type;

  change_tracking_modelRequest_()
    : filename()  {
    }
  change_tracking_modelRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filename_type;
  _filename_type filename;




  typedef boost::shared_ptr< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct change_tracking_modelRequest_

typedef ::object_tracker_srv_definitions::change_tracking_modelRequest_<std::allocator<void> > change_tracking_modelRequest;

typedef boost::shared_ptr< ::object_tracker_srv_definitions::change_tracking_modelRequest > change_tracking_modelRequestPtr;
typedef boost::shared_ptr< ::object_tracker_srv_definitions::change_tracking_modelRequest const> change_tracking_modelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_tracker_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_tracker_srv_definitions/change_tracking_modelRequest";
  }

  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n\
";
  }

  static const char* value(const ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct change_tracking_modelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_tracker_srv_definitions::change_tracking_modelRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_CHANGE_TRACKING_MODELREQUEST_H
