// Generated by gencpp from file object_tracker_srv_definitions/detect_and_track.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_DETECT_AND_TRACK_H
#define OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_DETECT_AND_TRACK_H

#include <ros/service_traits.h>


#include <object_tracker_srv_definitions/detect_and_trackRequest.h>
#include <object_tracker_srv_definitions/detect_and_trackResponse.h>


namespace object_tracker_srv_definitions
{

struct detect_and_track
{

typedef detect_and_trackRequest Request;
typedef detect_and_trackResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detect_and_track
} // namespace object_tracker_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_tracker_srv_definitions::detect_and_track > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::object_tracker_srv_definitions::detect_and_track&) { return value(); }
};

template<>
struct DataType< ::object_tracker_srv_definitions::detect_and_track > {
  static const char* value()
  {
    return "object_tracker_srv_definitions/detect_and_track";
  }

  static const char* value(const ::object_tracker_srv_definitions::detect_and_track&) { return value(); }
};


// service_traits::MD5Sum< ::object_tracker_srv_definitions::detect_and_trackRequest> should match 
// service_traits::MD5Sum< ::object_tracker_srv_definitions::detect_and_track > 
template<>
struct MD5Sum< ::object_tracker_srv_definitions::detect_and_trackRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_tracker_srv_definitions::detect_and_track >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::detect_and_trackRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_tracker_srv_definitions::detect_and_trackRequest> should match 
// service_traits::DataType< ::object_tracker_srv_definitions::detect_and_track > 
template<>
struct DataType< ::object_tracker_srv_definitions::detect_and_trackRequest>
{
  static const char* value()
  {
    return DataType< ::object_tracker_srv_definitions::detect_and_track >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::detect_and_trackRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_tracker_srv_definitions::detect_and_trackResponse> should match 
// service_traits::MD5Sum< ::object_tracker_srv_definitions::detect_and_track > 
template<>
struct MD5Sum< ::object_tracker_srv_definitions::detect_and_trackResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_tracker_srv_definitions::detect_and_track >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::detect_and_trackResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_tracker_srv_definitions::detect_and_trackResponse> should match 
// service_traits::DataType< ::object_tracker_srv_definitions::detect_and_track > 
template<>
struct DataType< ::object_tracker_srv_definitions::detect_and_trackResponse>
{
  static const char* value()
  {
    return DataType< ::object_tracker_srv_definitions::detect_and_track >::value();
  }
  static const char* value(const ::object_tracker_srv_definitions::detect_and_trackResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_TRACKER_SRV_DEFINITIONS_MESSAGE_DETECT_AND_TRACK_H
