// Generated by gencpp from file ros_to_cv_v2/Center.msg
// DO NOT EDIT!


#ifndef ROS_TO_CV_V2_MESSAGE_CENTER_H
#define ROS_TO_CV_V2_MESSAGE_CENTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_to_cv_v2
{
template <class ContainerAllocator>
struct Center_
{
  typedef Center_<ContainerAllocator> Type;

  Center_()
    : y(0)
    , x(0)  {
    }
  Center_(const ContainerAllocator& _alloc)
    : y(0)
    , x(0)  {
  (void)_alloc;
    }



   typedef int16_t _y_type;
  _y_type y;

   typedef int16_t _x_type;
  _x_type x;




  typedef boost::shared_ptr< ::ros_to_cv_v2::Center_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_to_cv_v2::Center_<ContainerAllocator> const> ConstPtr;

}; // struct Center_

typedef ::ros_to_cv_v2::Center_<std::allocator<void> > Center;

typedef boost::shared_ptr< ::ros_to_cv_v2::Center > CenterPtr;
typedef boost::shared_ptr< ::ros_to_cv_v2::Center const> CenterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_to_cv_v2::Center_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_to_cv_v2::Center_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_to_cv_v2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ros_to_cv_v2': ['/home/ros/catkin_ws/src/ros_to_cv_v2/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_to_cv_v2::Center_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_to_cv_v2::Center_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_to_cv_v2::Center_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_to_cv_v2::Center_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_to_cv_v2::Center_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_to_cv_v2::Center_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_to_cv_v2::Center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "509e6e8bf3c31440edeabf90a4adbb14";
  }

  static const char* value(const ::ros_to_cv_v2::Center_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x509e6e8bf3c31440ULL;
  static const uint64_t static_value2 = 0xedeabf90a4adbb14ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_to_cv_v2::Center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_to_cv_v2/Center";
  }

  static const char* value(const ::ros_to_cv_v2::Center_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_to_cv_v2::Center_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 y \n\
int16 x\n\
";
  }

  static const char* value(const ::ros_to_cv_v2::Center_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_to_cv_v2::Center_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Center_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_to_cv_v2::Center_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_to_cv_v2::Center_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TO_CV_V2_MESSAGE_CENTER_H
