// Generated by gencpp from file recognition_srv_definitions/get_configurationResponse.msg
// DO NOT EDIT!


#ifndef RECOGNITION_SRV_DEFINITIONS_MESSAGE_GET_CONFIGURATIONRESPONSE_H
#define RECOGNITION_SRV_DEFINITIONS_MESSAGE_GET_CONFIGURATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace recognition_srv_definitions
{
template <class ContainerAllocator>
struct get_configurationResponse_
{
  typedef get_configurationResponse_<ContainerAllocator> Type;

  get_configurationResponse_()
    : models_folder()  {
    }
  get_configurationResponse_(const ContainerAllocator& _alloc)
    : models_folder(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _models_folder_type;
  _models_folder_type models_folder;




  typedef boost::shared_ptr< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_configurationResponse_

typedef ::recognition_srv_definitions::get_configurationResponse_<std::allocator<void> > get_configurationResponse;

typedef boost::shared_ptr< ::recognition_srv_definitions::get_configurationResponse > get_configurationResponsePtr;
typedef boost::shared_ptr< ::recognition_srv_definitions::get_configurationResponse const> get_configurationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace recognition_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'object_perception_msgs': ['/home/ros/catkin_ws/src/v4r_ros_wrappers/object_perception_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13f7846c6d4d55da52d3bbdb9927422a";
  }

  static const char* value(const ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13f7846c6d4d55daULL;
  static const uint64_t static_value2 = 0x52d3bbdb9927422aULL;
};

template<class ContainerAllocator>
struct DataType< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recognition_srv_definitions/get_configurationResponse";
  }

  static const char* value(const ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String models_folder\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.models_folder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_configurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recognition_srv_definitions::get_configurationResponse_<ContainerAllocator>& v)
  {
    s << indent << "models_folder: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.models_folder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECOGNITION_SRV_DEFINITIONS_MESSAGE_GET_CONFIGURATIONRESPONSE_H
