// Generated by gencpp from file recognition_srv_definitions/recognizeResponse.msg
// DO NOT EDIT!


#ifndef RECOGNITION_SRV_DEFINITIONS_MESSAGE_RECOGNIZERESPONSE_H
#define RECOGNITION_SRV_DEFINITIONS_MESSAGE_RECOGNIZERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <geometry_msgs/Transform.h>
#include <geometry_msgs/Point32.h>
#include <object_perception_msgs/BBox.h>
#include <sensor_msgs/PointCloud2.h>

namespace recognition_srv_definitions
{
template <class ContainerAllocator>
struct recognizeResponse_
{
  typedef recognizeResponse_<ContainerAllocator> Type;

  recognizeResponse_()
    : ids()
    , transforms()
    , confidence()
    , centroid()
    , bbox()
    , models_cloud()  {
    }
  recognizeResponse_(const ContainerAllocator& _alloc)
    : ids(_alloc)
    , transforms(_alloc)
    , confidence(_alloc)
    , centroid(_alloc)
    , bbox(_alloc)
    , models_cloud(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _ids_type;
  _ids_type ids;

   typedef std::vector< ::geometry_msgs::Transform_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Transform_<ContainerAllocator> >::other >  _transforms_type;
  _transforms_type transforms;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _confidence_type;
  _confidence_type confidence;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point32_<ContainerAllocator> >::other >  _centroid_type;
  _centroid_type centroid;

   typedef std::vector< ::object_perception_msgs::BBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_perception_msgs::BBox_<ContainerAllocator> >::other >  _bbox_type;
  _bbox_type bbox;

   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _models_cloud_type;
  _models_cloud_type models_cloud;




  typedef boost::shared_ptr< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct recognizeResponse_

typedef ::recognition_srv_definitions::recognizeResponse_<std::allocator<void> > recognizeResponse;

typedef boost::shared_ptr< ::recognition_srv_definitions::recognizeResponse > recognizeResponsePtr;
typedef boost::shared_ptr< ::recognition_srv_definitions::recognizeResponse const> recognizeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace recognition_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'object_perception_msgs': ['/home/ros/catkin_ws/src/v4r_ros_wrappers/object_perception_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba0a550a719b89767d1fc450f48b2b01";
  }

  static const char* value(const ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba0a550a719b8976ULL;
  static const uint64_t static_value2 = 0x7d1fc450f48b2b01ULL;
};

template<class ContainerAllocator>
struct DataType< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recognition_srv_definitions/recognizeResponse";
  }

  static const char* value(const ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String[] ids\n\
geometry_msgs/Transform[] transforms\n\
\n\
\n\
float32[] confidence\n\
\n\
\n\
geometry_msgs/Point32[] centroid\n\
\n\
\n\
object_perception_msgs/BBox[] bbox\n\
\n\
\n\
sensor_msgs/PointCloud2[] models_cloud\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: object_perception_msgs/BBox\n\
# 8 points of the bounding box\n\
geometry_msgs/Point32[] point\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
";
  }

  static const char* value(const ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
      stream.next(m.transforms);
      stream.next(m.confidence);
      stream.next(m.centroid);
      stream.next(m.bbox);
      stream.next(m.models_cloud);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct recognizeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recognition_srv_definitions::recognizeResponse_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.ids[i]);
    }
    s << indent << "transforms[]" << std::endl;
    for (size_t i = 0; i < v.transforms.size(); ++i)
    {
      s << indent << "  transforms[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "    ", v.transforms[i]);
    }
    s << indent << "confidence[]" << std::endl;
    for (size_t i = 0; i < v.confidence.size(); ++i)
    {
      s << indent << "  confidence[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidence[i]);
    }
    s << indent << "centroid[]" << std::endl;
    for (size_t i = 0; i < v.centroid.size(); ++i)
    {
      s << indent << "  centroid[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.centroid[i]);
    }
    s << indent << "bbox[]" << std::endl;
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      s << indent << "  bbox[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_perception_msgs::BBox_<ContainerAllocator> >::stream(s, indent + "    ", v.bbox[i]);
    }
    s << indent << "models_cloud[]" << std::endl;
    for (size_t i = 0; i < v.models_cloud.size(); ++i)
    {
      s << indent << "  models_cloud[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.models_cloud[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECOGNITION_SRV_DEFINITIONS_MESSAGE_RECOGNIZERESPONSE_H
