// Generated by gencpp from file recognition_srv_definitions/recognize.msg
// DO NOT EDIT!


#ifndef RECOGNITION_SRV_DEFINITIONS_MESSAGE_RECOGNIZE_H
#define RECOGNITION_SRV_DEFINITIONS_MESSAGE_RECOGNIZE_H

#include <ros/service_traits.h>


#include <recognition_srv_definitions/recognizeRequest.h>
#include <recognition_srv_definitions/recognizeResponse.h>


namespace recognition_srv_definitions
{

struct recognize
{

typedef recognizeRequest Request;
typedef recognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct recognize
} // namespace recognition_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::recognition_srv_definitions::recognize > {
  static const char* value()
  {
    return "2f9dd9890b8259b9dae06acc569790f2";
  }

  static const char* value(const ::recognition_srv_definitions::recognize&) { return value(); }
};

template<>
struct DataType< ::recognition_srv_definitions::recognize > {
  static const char* value()
  {
    return "recognition_srv_definitions/recognize";
  }

  static const char* value(const ::recognition_srv_definitions::recognize&) { return value(); }
};


// service_traits::MD5Sum< ::recognition_srv_definitions::recognizeRequest> should match 
// service_traits::MD5Sum< ::recognition_srv_definitions::recognize > 
template<>
struct MD5Sum< ::recognition_srv_definitions::recognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::recognition_srv_definitions::recognize >::value();
  }
  static const char* value(const ::recognition_srv_definitions::recognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::recognition_srv_definitions::recognizeRequest> should match 
// service_traits::DataType< ::recognition_srv_definitions::recognize > 
template<>
struct DataType< ::recognition_srv_definitions::recognizeRequest>
{
  static const char* value()
  {
    return DataType< ::recognition_srv_definitions::recognize >::value();
  }
  static const char* value(const ::recognition_srv_definitions::recognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::recognition_srv_definitions::recognizeResponse> should match 
// service_traits::MD5Sum< ::recognition_srv_definitions::recognize > 
template<>
struct MD5Sum< ::recognition_srv_definitions::recognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::recognition_srv_definitions::recognize >::value();
  }
  static const char* value(const ::recognition_srv_definitions::recognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::recognition_srv_definitions::recognizeResponse> should match 
// service_traits::DataType< ::recognition_srv_definitions::recognize > 
template<>
struct DataType< ::recognition_srv_definitions::recognizeResponse>
{
  static const char* value()
  {
    return DataType< ::recognition_srv_definitions::recognize >::value();
  }
  static const char* value(const ::recognition_srv_definitions::recognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RECOGNITION_SRV_DEFINITIONS_MESSAGE_RECOGNIZE_H
