// Generated by gencpp from file recognition_srv_definitions/retrain_recognizerResponse.msg
// DO NOT EDIT!


#ifndef RECOGNITION_SRV_DEFINITIONS_MESSAGE_RETRAIN_RECOGNIZERRESPONSE_H
#define RECOGNITION_SRV_DEFINITIONS_MESSAGE_RETRAIN_RECOGNIZERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace recognition_srv_definitions
{
template <class ContainerAllocator>
struct retrain_recognizerResponse_
{
  typedef retrain_recognizerResponse_<ContainerAllocator> Type;

  retrain_recognizerResponse_()
    {
    }
  retrain_recognizerResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct retrain_recognizerResponse_

typedef ::recognition_srv_definitions::retrain_recognizerResponse_<std::allocator<void> > retrain_recognizerResponse;

typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerResponse > retrain_recognizerResponsePtr;
typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerResponse const> retrain_recognizerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace recognition_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'object_perception_msgs': ['/home/ros/catkin_ws/src/v4r_ros_wrappers/object_perception_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recognition_srv_definitions/retrain_recognizerResponse";
  }

  static const char* value(const ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct retrain_recognizerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::recognition_srv_definitions::retrain_recognizerResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RECOGNITION_SRV_DEFINITIONS_MESSAGE_RETRAIN_RECOGNIZERRESPONSE_H
