// Generated by gencpp from file recognition_srv_definitions/retrain_recognizerRequest.msg
// DO NOT EDIT!


#ifndef RECOGNITION_SRV_DEFINITIONS_MESSAGE_RETRAIN_RECOGNIZERREQUEST_H
#define RECOGNITION_SRV_DEFINITIONS_MESSAGE_RETRAIN_RECOGNIZERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace recognition_srv_definitions
{
template <class ContainerAllocator>
struct retrain_recognizerRequest_
{
  typedef retrain_recognizerRequest_<ContainerAllocator> Type;

  retrain_recognizerRequest_()
    : load_ids()  {
    }
  retrain_recognizerRequest_(const ContainerAllocator& _alloc)
    : load_ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _load_ids_type;
  _load_ids_type load_ids;




  typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct retrain_recognizerRequest_

typedef ::recognition_srv_definitions::retrain_recognizerRequest_<std::allocator<void> > retrain_recognizerRequest;

typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerRequest > retrain_recognizerRequestPtr;
typedef boost::shared_ptr< ::recognition_srv_definitions::retrain_recognizerRequest const> retrain_recognizerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace recognition_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'object_perception_msgs': ['/home/ros/catkin_ws/src/v4r_ros_wrappers/object_perception_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68f1a1137280e26bfbb288099ac3fce1";
  }

  static const char* value(const ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68f1a1137280e26bULL;
  static const uint64_t static_value2 = 0xfbb288099ac3fce1ULL;
};

template<class ContainerAllocator>
struct DataType< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "recognition_srv_definitions/retrain_recognizerRequest";
  }

  static const char* value(const ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/String[] load_ids\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.load_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct retrain_recognizerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::recognition_srv_definitions::retrain_recognizerRequest_<ContainerAllocator>& v)
  {
    s << indent << "load_ids[]" << std::endl;
    for (size_t i = 0; i < v.load_ids.size(); ++i)
    {
      s << indent << "  load_ids[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.load_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RECOGNITION_SRV_DEFINITIONS_MESSAGE_RETRAIN_RECOGNIZERREQUEST_H
