// Generated by gencpp from file segmentation_srv_definitions/MS_segmentResponse.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_SRV_DEFINITIONS_MESSAGE_MS_SEGMENTRESPONSE_H
#define SEGMENTATION_SRV_DEFINITIONS_MESSAGE_MS_SEGMENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32MultiArray.h>

namespace segmentation_srv_definitions
{
template <class ContainerAllocator>
struct MS_segmentResponse_
{
  typedef MS_segmentResponse_<ContainerAllocator> Type;

  MS_segmentResponse_()
    : clusters_indices()  {
    }
  MS_segmentResponse_(const ContainerAllocator& _alloc)
    : clusters_indices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::Int32MultiArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Int32MultiArray_<ContainerAllocator> >::other >  _clusters_indices_type;
  _clusters_indices_type clusters_indices;




  typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MS_segmentResponse_

typedef ::segmentation_srv_definitions::MS_segmentResponse_<std::allocator<void> > MS_segmentResponse;

typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentResponse > MS_segmentResponsePtr;
typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentResponse const> MS_segmentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33486b2fa5daf06d318d0c177eb58481";
  }

  static const char* value(const ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33486b2fa5daf06dULL;
  static const uint64_t static_value2 = 0x318d0c177eb58481ULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation_srv_definitions/MS_segmentResponse";
  }

  static const char* value(const ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32MultiArray[] clusters_indices\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
int32[]           data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clusters_indices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MS_segmentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation_srv_definitions::MS_segmentResponse_<ContainerAllocator>& v)
  {
    s << indent << "clusters_indices[]" << std::endl;
    for (size_t i = 0; i < v.clusters_indices.size(); ++i)
    {
      s << indent << "  clusters_indices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Int32MultiArray_<ContainerAllocator> >::stream(s, indent + "    ", v.clusters_indices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_SRV_DEFINITIONS_MESSAGE_MS_SEGMENTRESPONSE_H
