// Generated by gencpp from file segmentation_srv_definitions/MS_segmentRequest.msg
// DO NOT EDIT!


#ifndef SEGMENTATION_SRV_DEFINITIONS_MESSAGE_MS_SEGMENTREQUEST_H
#define SEGMENTATION_SRV_DEFINITIONS_MESSAGE_MS_SEGMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>
#include <std_msgs/Int32.h>
#include <std_msgs/Bool.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Bool.h>

namespace segmentation_srv_definitions
{
template <class ContainerAllocator>
struct MS_segmentRequest_
{
  typedef MS_segmentRequest_<ContainerAllocator> Type;

  MS_segmentRequest_()
    : cloud()
    , max_mt()
    , refinement()
    , nyu()
    , lambda()
    , sv_seed()
    , sv_res()
    , use_SLIC()  {
    }
  MS_segmentRequest_(const ContainerAllocator& _alloc)
    : cloud(_alloc)
    , max_mt(_alloc)
    , refinement(_alloc)
    , nyu(_alloc)
    , lambda(_alloc)
    , sv_seed(_alloc)
    , sv_res(_alloc)
    , use_SLIC(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_type;
  _cloud_type cloud;

   typedef  ::std_msgs::Int32_<ContainerAllocator>  _max_mt_type;
  _max_mt_type max_mt;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _refinement_type;
  _refinement_type refinement;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _nyu_type;
  _nyu_type nyu;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _lambda_type;
  _lambda_type lambda;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _sv_seed_type;
  _sv_seed_type sv_seed;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _sv_res_type;
  _sv_res_type sv_res;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _use_SLIC_type;
  _use_SLIC_type use_SLIC;




  typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MS_segmentRequest_

typedef ::segmentation_srv_definitions::MS_segmentRequest_<std::allocator<void> > MS_segmentRequest;

typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentRequest > MS_segmentRequestPtr;
typedef boost::shared_ptr< ::segmentation_srv_definitions::MS_segmentRequest const> MS_segmentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace segmentation_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bb0c6a4d517a84c22628c95a7a7694e0";
  }

  static const char* value(const ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbb0c6a4d517a84c2ULL;
  static const uint64_t static_value2 = 0x2628c95a7a7694e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "segmentation_srv_definitions/MS_segmentRequest";
  }

  static const char* value(const ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/PointCloud2 cloud\n\
std_msgs/Int32 max_mt\n\
std_msgs/Bool refinement\n\
std_msgs/Float32 nyu\n\
std_msgs/Float32 lambda\n\
std_msgs/Float32 sv_seed\n\
std_msgs/Float32 sv_res\n\
std_msgs/Bool use_SLIC\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cloud);
      stream.next(m.max_mt);
      stream.next(m.refinement);
      stream.next(m.nyu);
      stream.next(m.lambda);
      stream.next(m.sv_seed);
      stream.next(m.sv_res);
      stream.next(m.use_SLIC);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MS_segmentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::segmentation_srv_definitions::MS_segmentRequest_<ContainerAllocator>& v)
  {
    s << indent << "cloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud);
    s << indent << "max_mt: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.max_mt);
    s << indent << "refinement: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.refinement);
    s << indent << "nyu: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.nyu);
    s << indent << "lambda: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.lambda);
    s << indent << "sv_seed: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.sv_seed);
    s << indent << "sv_res: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.sv_res);
    s << indent << "use_SLIC: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.use_SLIC);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATION_SRV_DEFINITIONS_MESSAGE_MS_SEGMENTREQUEST_H
