// Generated by gencpp from file object_perception_msgs/classification.msg
// DO NOT EDIT!


#ifndef OBJECT_PERCEPTION_MSGS_MESSAGE_CLASSIFICATION_H
#define OBJECT_PERCEPTION_MSGS_MESSAGE_CLASSIFICATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace object_perception_msgs
{
template <class ContainerAllocator>
struct classification_
{
  typedef classification_<ContainerAllocator> Type;

  classification_()
    : class_type()
    , confidence()  {
    }
  classification_(const ContainerAllocator& _alloc)
    : class_type(_alloc)
    , confidence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::String_<ContainerAllocator> >::other >  _class_type_type;
  _class_type_type class_type;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _confidence_type;
  _confidence_type confidence;




  typedef boost::shared_ptr< ::object_perception_msgs::classification_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_perception_msgs::classification_<ContainerAllocator> const> ConstPtr;

}; // struct classification_

typedef ::object_perception_msgs::classification_<std::allocator<void> > classification;

typedef boost::shared_ptr< ::object_perception_msgs::classification > classificationPtr;
typedef boost::shared_ptr< ::object_perception_msgs::classification const> classificationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_perception_msgs::classification_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_perception_msgs::classification_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_perception_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'object_perception_msgs': ['/home/ros/catkin_ws/src/v4r_ros_wrappers/object_perception_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_perception_msgs::classification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_perception_msgs::classification_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_perception_msgs::classification_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_perception_msgs::classification_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_perception_msgs::classification_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_perception_msgs::classification_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_perception_msgs::classification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "308b8cac9a8165761785459122dd097d";
  }

  static const char* value(const ::object_perception_msgs::classification_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x308b8cac9a816576ULL;
  static const uint64_t static_value2 = 0x1785459122dd097dULL;
};

template<class ContainerAllocator>
struct DataType< ::object_perception_msgs::classification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_perception_msgs/classification";
  }

  static const char* value(const ::object_perception_msgs::classification_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_perception_msgs::classification_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String[] class_type\n\
float32[] confidence\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::object_perception_msgs::classification_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_perception_msgs::classification_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_type);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct classification_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_perception_msgs::classification_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_perception_msgs::classification_<ContainerAllocator>& v)
  {
    s << indent << "class_type[]" << std::endl;
    for (size_t i = 0; i < v.class_type.size(); ++i)
    {
      s << indent << "  class_type[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.class_type[i]);
    }
    s << indent << "confidence[]" << std::endl;
    for (size_t i = 0; i < v.confidence.size(); ++i)
    {
      s << indent << "  confidence[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.confidence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_PERCEPTION_MSGS_MESSAGE_CLASSIFICATION_H
