(cl:defpackage recognition_srv_definitions-srv
  (:use )
  (:export
   "RECOGNIZE"
   "<RECOGNIZE-REQUEST>"
   "RECOGNIZE-REQUEST"
   "<RECOGNIZE-RESPONSE>"
   "RECOGNIZE-RESPONSE"
   "RETRAIN_RECOGNIZER"
   "<RETRAIN_RECOGNIZER-REQUEST>"
   "RETRAIN_RECOGNIZER-REQUEST"
   "<RETRAIN_RECOGNIZER-RESPONSE>"
   "RETRAIN_RECOGNIZER-RESPONSE"
   "GET_CONFIGURATION"
   "<GET_CONFIGURATION-REQUEST>"
   "GET_CONFIGURATION-REQUEST"
   "<GET_CONFIGURATION-RESPONSE>"
   "GET_CONFIGURATION-RESPONSE"
  ))

