// Generated by gencpp from file incremental_object_learning_srv_definitions/clearResponse.msg
// DO NOT EDIT!


#ifndef INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_CLEARRESPONSE_H
#define INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_CLEARRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace incremental_object_learning_srv_definitions
{
template <class ContainerAllocator>
struct clearResponse_
{
  typedef clearResponse_<ContainerAllocator> Type;

  clearResponse_()
    {
    }
  clearResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> const> ConstPtr;

}; // struct clearResponse_

typedef ::incremental_object_learning_srv_definitions::clearResponse_<std::allocator<void> > clearResponse;

typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::clearResponse > clearResponsePtr;
typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::clearResponse const> clearResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace incremental_object_learning_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "incremental_object_learning_srv_definitions/clearResponse";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct clearResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::incremental_object_learning_srv_definitions::clearResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_CLEARRESPONSE_H
