// Generated by gencpp from file incremental_object_learning_srv_definitions/learn_object_inc.msg
// DO NOT EDIT!


#ifndef INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_LEARN_OBJECT_INC_H
#define INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_LEARN_OBJECT_INC_H

#include <ros/service_traits.h>


#include <incremental_object_learning_srv_definitions/learn_object_incRequest.h>
#include <incremental_object_learning_srv_definitions/learn_object_incResponse.h>


namespace incremental_object_learning_srv_definitions
{

struct learn_object_inc
{

typedef learn_object_incRequest Request;
typedef learn_object_incResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct learn_object_inc
} // namespace incremental_object_learning_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_inc > {
  static const char* value()
  {
    return "c22326b5af8643bca97132dd41d1c7fa";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object_inc&) { return value(); }
};

template<>
struct DataType< ::incremental_object_learning_srv_definitions::learn_object_inc > {
  static const char* value()
  {
    return "incremental_object_learning_srv_definitions/learn_object_inc";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object_inc&) { return value(); }
};


// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_incRequest> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_inc > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_incRequest>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_inc >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object_incRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_object_incRequest> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_object_inc > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::learn_object_incRequest>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::learn_object_inc >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object_incRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_incResponse> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_inc > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_incResponse>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::learn_object_inc >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object_incResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_object_incResponse> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_object_inc > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::learn_object_incResponse>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::learn_object_inc >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object_incResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_LEARN_OBJECT_INC_H
