// Generated by gencpp from file incremental_object_learning_srv_definitions/learn_object.msg
// DO NOT EDIT!


#ifndef INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_LEARN_OBJECT_H
#define INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_LEARN_OBJECT_H

#include <ros/service_traits.h>


#include <incremental_object_learning_srv_definitions/learn_objectRequest.h>
#include <incremental_object_learning_srv_definitions/learn_objectResponse.h>


namespace incremental_object_learning_srv_definitions
{

struct learn_object
{

typedef learn_objectRequest Request;
typedef learn_objectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct learn_object
} // namespace incremental_object_learning_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::learn_object > {
  static const char* value()
  {
    return "44dd9257f52ea9231403037ca8d8433e";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object&) { return value(); }
};

template<>
struct DataType< ::incremental_object_learning_srv_definitions::learn_object > {
  static const char* value()
  {
    return "incremental_object_learning_srv_definitions/learn_object";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::learn_object&) { return value(); }
};


// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_objectRequest> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_object > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::learn_objectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::learn_object >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_objectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_objectRequest> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_object > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::learn_objectRequest>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::learn_object >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_objectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_objectResponse> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::learn_object > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::learn_objectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::learn_object >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_objectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_objectResponse> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::learn_object > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::learn_objectResponse>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::learn_object >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::learn_objectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_LEARN_OBJECT_H
