// Generated by gencpp from file incremental_object_learning_srv_definitions/save_modelRequest.msg
// DO NOT EDIT!


#ifndef INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_SAVE_MODELREQUEST_H
#define INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_SAVE_MODELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/String.h>

namespace incremental_object_learning_srv_definitions
{
template <class ContainerAllocator>
struct save_modelRequest_
{
  typedef save_modelRequest_<ContainerAllocator> Type;

  save_modelRequest_()
    : object_name()
    , models_folder()  {
    }
  save_modelRequest_(const ContainerAllocator& _alloc)
    : object_name(_alloc)
    , models_folder(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _object_name_type;
  _object_name_type object_name;

   typedef  ::std_msgs::String_<ContainerAllocator>  _models_folder_type;
  _models_folder_type models_folder;




  typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct save_modelRequest_

typedef ::incremental_object_learning_srv_definitions::save_modelRequest_<std::allocator<void> > save_modelRequest;

typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::save_modelRequest > save_modelRequestPtr;
typedef boost::shared_ptr< ::incremental_object_learning_srv_definitions::save_modelRequest const> save_modelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace incremental_object_learning_srv_definitions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c8027a149addfd48596c5dfccb5d5db";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c8027a149addfd4ULL;
  static const uint64_t static_value2 = 0x8596c5dfccb5d5dbULL;
};

template<class ContainerAllocator>
struct DataType< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "incremental_object_learning_srv_definitions/save_modelRequest";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/String object_name\n\
\n\
std_msgs/String models_folder\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_name);
      stream.next(m.models_folder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct save_modelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::incremental_object_learning_srv_definitions::save_modelRequest_<ContainerAllocator>& v)
  {
    s << indent << "object_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.object_name);
    s << indent << "models_folder: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.models_folder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_SAVE_MODELREQUEST_H
