// Generated by gencpp from file incremental_object_learning_srv_definitions/save_model.msg
// DO NOT EDIT!


#ifndef INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_SAVE_MODEL_H
#define INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_SAVE_MODEL_H

#include <ros/service_traits.h>


#include <incremental_object_learning_srv_definitions/save_modelRequest.h>
#include <incremental_object_learning_srv_definitions/save_modelResponse.h>


namespace incremental_object_learning_srv_definitions
{

struct save_model
{

typedef save_modelRequest Request;
typedef save_modelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct save_model
} // namespace incremental_object_learning_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::save_model > {
  static const char* value()
  {
    return "7c8027a149addfd48596c5dfccb5d5db";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::save_model&) { return value(); }
};

template<>
struct DataType< ::incremental_object_learning_srv_definitions::save_model > {
  static const char* value()
  {
    return "incremental_object_learning_srv_definitions/save_model";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::save_model&) { return value(); }
};


// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::save_modelRequest> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::save_model > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::save_modelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::save_model >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::save_modelRequest> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::save_model > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::save_modelRequest>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::save_model >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::save_modelResponse> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::save_model > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::save_modelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::save_model >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::save_modelResponse> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::save_model > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::save_modelResponse>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::save_model >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::save_modelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_SAVE_MODEL_H
