// Generated by gencpp from file incremental_object_learning_srv_definitions/visualize.msg
// DO NOT EDIT!


#ifndef INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_VISUALIZE_H
#define INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_VISUALIZE_H

#include <ros/service_traits.h>


#include <incremental_object_learning_srv_definitions/visualizeRequest.h>
#include <incremental_object_learning_srv_definitions/visualizeResponse.h>


namespace incremental_object_learning_srv_definitions
{

struct visualize
{

typedef visualizeRequest Request;
typedef visualizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visualize
} // namespace incremental_object_learning_srv_definitions


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::visualize > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::visualize&) { return value(); }
};

template<>
struct DataType< ::incremental_object_learning_srv_definitions::visualize > {
  static const char* value()
  {
    return "incremental_object_learning_srv_definitions/visualize";
  }

  static const char* value(const ::incremental_object_learning_srv_definitions::visualize&) { return value(); }
};


// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::visualizeRequest> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::visualize > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::visualizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::visualize >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::visualizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::visualizeRequest> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::visualize > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::visualizeRequest>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::visualize >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::visualizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::visualizeResponse> should match 
// service_traits::MD5Sum< ::incremental_object_learning_srv_definitions::visualize > 
template<>
struct MD5Sum< ::incremental_object_learning_srv_definitions::visualizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::incremental_object_learning_srv_definitions::visualize >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::visualizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::incremental_object_learning_srv_definitions::visualizeResponse> should match 
// service_traits::DataType< ::incremental_object_learning_srv_definitions::visualize > 
template<>
struct DataType< ::incremental_object_learning_srv_definitions::visualizeResponse>
{
  static const char* value()
  {
    return DataType< ::incremental_object_learning_srv_definitions::visualize >::value();
  }
  static const char* value(const ::incremental_object_learning_srv_definitions::visualizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INCREMENTAL_OBJECT_LEARNING_SRV_DEFINITIONS_MESSAGE_VISUALIZE_H
